### ISSUE TITLE
CSS 常见布局：左侧固定右侧自适应

### ISSUE THREAD

**Issue by wjlscript** [wjlscript/wjlscriptblog#6]
### 前言

左侧固定右侧自适应，这种布局在网页中极为常见。如左侧导航固定，右侧内容自适应。当然也可以反过来，左侧自适应右侧固定。

以下为 html 布局：

```html
<div class="outer">
  <div class="sidebar">固定宽度区</div>
  <div class="content">自适应区</div>
</div>
```

### 方法一：固定区浮动，自适应区设置外边距

```css
.sidebar {
  width: 300px;
  height: 300px;
  background-color: pink;
  float: left;
}

.content {
  margin-left: 300px;
  height: 300px;
  background-color: blue;
}

.outer{
  overflow: hidden;
}
```

需要注意的是，这种方法有一个缺陷，即浮动的 sidebar 在 html 结构上必须位于 content 之前

### 方法二：固定区绝对定位，自适应区设置外边距

```css
.sidebar {
  width: 300px;
  height: 300px;
  background-color: pink;
  position: absolute;
  top: 0;
  left: 0;

}

.content {
  height: 300px;
  background-color: blue;
}

.outer {
  position: relative;
}
```

需要注意的是，这种方法如果两个区域的高度不同，那么有可能会对后面的元素产生影响。例如，当固定区高度大于自适应区高度的时候，固定区会覆盖后面的元素。

### 方法三：使用 tabel 和 tabel-cell

```css
.sidebar {
  width: 300px;
  height: 300px;
  background-color: pink;
  display: table-cell;

}

.content {
  height: 300px;
  background-color: blue;
  display: table-cell;
}

.outer {
  display: table;
  width: 100%;
}
```

需要注意的是，这种方法会导致两个区域的高度一致，其高度值取决于数值较大的一个。
